### ISSUE TITLE
IP address

### ISSUE THREAD

**Issue by jakjr** [mintbridge/eloquent-auditing#1]
Hi,

the IP address of the Auditor class is not automatic filled.

I need to change the class to:
```
        // save change data with event
        $action = new Activity([
            'event' => $eventName,
            'data'  => $model->getDirty(),
            'ip_address' => Request::ip(),
        ]);
```
ou put nullable at the migration file.

Thanks

**Comment by mintbridge** [comment]
Thanks, i've done both in the v0.0.5 version
